/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** GET /api/health — public · data.service ต้องตรงกับ name ใน subsystem.yaml */
        get: operations["HealthController_health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ตัวตนของผู้ใช้ปัจจุบัน + role/permission ภายในร้านค้า */
        get: operations["MeController_me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการสินค้า (แบ่งหน้า) */
        get: operations["ProductsController_findAll"];
        put?: never;
        /** เพิ่มสินค้า (เจ้าหน้าที่) */
        post: operations["ProductsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/products/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** สินค้าหนึ่งรายการพร้อมตัวเลือก */
        get: operations["ProductsController_findOne"];
        put?: never;
        post?: never;
        /** ลบสินค้า (ผู้ดูแล) — ลบไม่ได้ถ้าเคยถูกสั่งซื้อแล้ว */
        delete: operations["ProductsController_remove"];
        options?: never;
        head?: never;
        /** แก้ไขสินค้าบางฟิลด์ (เจ้าหน้าที่) */
        patch: operations["ProductsController_update"];
        trace?: never;
    };
    "/api/v1/product-categories": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** หมวดหมู่สินค้าพร้อมจำนวนสินค้าในแต่ละหมวด */
        get: operations["ProductCategoriesController_findAll"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-variants": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการตัวเลือกสินค้า (ใช้หน้าจัดการสต็อก) */
        get: operations["ProductVariantsController_findAll"];
        put?: never;
        /** เพิ่มตัวเลือกให้สินค้า (เจ้าหน้าที่) */
        post: operations["ProductVariantsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-variants/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["ProductVariantsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["ProductVariantsController_remove"];
        options?: never;
        head?: never;
        patch: operations["ProductVariantsController_update"];
        trace?: never;
    };
    "/api/v1/product-variants/{id}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ปรับสต็อก (เพิ่ม/ลด หรือกำหนดค่า) */
        patch: operations["ProductVariantsController_updateStock"];
        trace?: never;
    };
    "/api/v1/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการคำสั่งซื้อ — ลูกค้าเห็นเฉพาะของตัวเอง เจ้าหน้าที่เห็นทั้งหมด */
        get: operations["OrdersController_findAll"];
        put?: never;
        /** สั่งซื้อ — เจ้าของคือผู้ที่ login อยู่ */
        post: operations["OrdersController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrdersController_findOne"];
        put?: never;
        post?: never;
        /** ลบคำสั่งซื้อ (ผู้ดูแล) */
        delete: operations["OrdersController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/orders/{id}/payment-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** ตรวจสลิป / เปลี่ยนสถานะการชำระเงิน (เจ้าหน้าที่) */
        patch: operations["OrdersController_updatePaymentStatus"];
        trace?: never;
    };
    "/api/v1/orders/{id}/order-status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** เปลี่ยนสถานะคำสั่งซื้อ (เจ้าหน้าที่) — ยกเลิกแล้วคืนสต็อก */
        patch: operations["OrdersController_updateOrderStatus"];
        trace?: never;
    };
    "/api/v1/orders/{id}/shipping": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** บริษัทขนส่ง + เลขพัสดุ (เฉพาะแบบจัดส่ง) */
        patch: operations["OrdersController_updateShipping"];
        trace?: never;
    };
    "/api/v1/orders/{id}/payment-slip": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** แนบสลิปการชำระเงิน — เจ้าของคำสั่งซื้อ */
        patch: operations["OrdersController_updatePaymentSlip"];
        trace?: never;
    };
    "/api/v1/orders/{id}/items": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** รายการสินค้าในคำสั่งซื้อ */
        get: operations["OrdersController_findItems"];
        put?: never;
        /** เพิ่มสินค้าเข้าคำสั่งซื้อ (เจ้าหน้าที่) */
        post: operations["OrdersController_addItem"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order-items/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["OrderItemsController_findOne"];
        put?: never;
        post?: never;
        /** ลบรายการและคืนสต็อก (เจ้าหน้าที่) */
        delete: operations["OrderItemsController_remove"];
        options?: never;
        head?: never;
        /** แก้จำนวน (เจ้าหน้าที่) */
        patch: operations["OrderItemsController_update"];
        trace?: never;
    };
    "/api/v1/pickup-logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PickupLogsController_findAll"];
        put?: never;
        /** บันทึกการส่งมอบสินค้า (เจ้าหน้าที่) — ปิดคำสั่งซื้อเป็น COMPLETED */
        post: operations["PickupLogsController_create"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pickup-logs/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["PickupLogsController_findOne"];
        put?: never;
        post?: never;
        delete: operations["PickupLogsController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/pickup-verifications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["PickupVerificationsController_verify"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/order-stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** ภาพรวมยอดขายและจำนวนคำสั่งซื้อตามสถานะ (หน้าแดชบอร์ดเจ้าหน้าที่) */
        get: operations["OrderStatsController_summary"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-images": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * อัปโหลดรูปสินค้า (multipart/form-data ฟิลด์ชื่อ file) → คืน url ไปใส่ imageUrl ของสินค้า
         *     เก็บไฟล์ในดิสก์ ฐานข้อมูลเก็บแค่ที่อยู่ไฟล์
         */
        post: operations["ProductImagesController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/product-images/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** ลบรูปที่ไม่ใช้แล้ว */
        delete: operations["ProductImagesController_remove"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/payment-slips": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * อัปโหลดสลิปโอนเงิน (multipart/form-data ฟิลด์ชื่อ file) → คืน url ไปใส่ paymentSlip ของคำสั่งซื้อ
         *     สลิปเป็นเอกสารการเงิน จึงเก็บในดิสก์และเปิดดูผ่าน GET ที่ตรวจสิทธิ์ทุกครั้ง (ไม่มี static)
         */
        post: operations["PaymentSlipsController_upload"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthModel: {
            /** @enum {string} */
            status: "ok";
            /** @enum {string} */
            database: "up" | "down";
            service: string;
        };
        PageMetaModel: {
            total: number;
            page: number;
            limit: number;
            totalPages: number;
        };
        MeModel: {
            permissions: string[];
            /** @description claim `sub` ของ Core Hub */
            id: string;
            email: string;
            /** @description student · alumni · staff · admin */
            coreRole: string;
            /** @description STUDENT · ALUMNI · STAFF · ADMIN */
            subsystemRole: string;
            /** @description เวลาที่ session (Core Hub token) หมดอายุ */
            expiresAt: string;
        };
        ProductVariantModel: {
            id: string;
            productId: string;
            variantName: string;
            /** @description ราคาต่อชิ้น หน่วยสตางค์ */
            price: number;
            /** @description ติดลบได้เฉพาะสินค้าพรีออเดอร์ (= ยอดที่ต้องสั่งผลิตเพิ่ม) */
            stockQuantity: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        ProductModel: {
            description: string | null;
            imageUrl: string | null;
            /** Format: date-time */
            preorderEndDate: string | null;
            /**
             * Format: date
             * @description YYYY-MM-DD
             */
            estimatedDelivery: string | null;
            variants: components["schemas"]["ProductVariantModel"][];
            id: string;
            name: string;
            category: string;
            isPreorder: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateProductVariantInlineDto: {
            /** @description ชื่อตัวเลือก เช่น "M" หรือ "ดำ / L" */
            variantName: string;
            /** @description ราคาต่อชิ้น หน่วยสตางค์ (เช่น 25000 = 250 บาท) */
            price: number;
            /** @description จำนวนคงเหลือเริ่มต้น */
            stockQuantity?: number;
        };
        CreateProductDto: {
            /** @description ชื่อสินค้า */
            name: string;
            /** @description รายละเอียดสินค้า */
            description?: string;
            /** @description หมวดหมู่ เช่น "เสื้อ" "ของที่ระลึก" */
            category: string;
            /** @description URL รูปที่ได้จาก POST /api/v1/product-images (ส่ง "" เพื่อเอารูปออก) */
            imageUrl?: string;
            /** @description เป็นสินค้าพรีออเดอร์หรือไม่ */
            isPreorder?: boolean;
            /** @description วันปิดรับพรีออเดอร์ (ISO 8601) — บังคับเมื่อ isPreorder = true · ส่ง "" เพื่อล้างค่า */
            preorderEndDate?: string;
            /** @description วันที่คาดว่าจะได้รับสินค้า (YYYY-MM-DD) · ส่ง "" เพื่อล้างค่า */
            estimatedDelivery?: string;
            /** @description ตัวเลือกสินค้าเริ่มต้น */
            variants?: components["schemas"]["CreateProductVariantInlineDto"][];
        };
        UpdateProductDto: {
            /** @description ชื่อสินค้า */
            name?: string;
            /** @description รายละเอียดสินค้า */
            description?: string;
            /** @description หมวดหมู่ เช่น "เสื้อ" "ของที่ระลึก" */
            category?: string;
            /** @description URL รูปที่ได้จาก POST /api/v1/product-images (ส่ง "" เพื่อเอารูปออก) */
            imageUrl?: string;
            /** @description เป็นสินค้าพรีออเดอร์หรือไม่ */
            isPreorder?: boolean;
            /** @description วันปิดรับพรีออเดอร์ (ISO 8601) — บังคับเมื่อ isPreorder = true · ส่ง "" เพื่อล้างค่า */
            preorderEndDate?: string;
            /** @description วันที่คาดว่าจะได้รับสินค้า (YYYY-MM-DD) · ส่ง "" เพื่อล้างค่า */
            estimatedDelivery?: string;
        };
        DeletedModel: {
            /** @enum {boolean} */
            deleted: true;
            id: string;
        };
        ProductCategoryModel: {
            category: string;
            productCount: number;
        };
        ProductSummaryModel: {
            imageUrl: string | null;
            id: string;
            name: string;
            category: string;
            isPreorder: boolean;
        };
        VariantWithProductModel: {
            product: components["schemas"]["ProductSummaryModel"];
            id: string;
            productId: string;
            variantName: string;
            /** @description ราคาต่อชิ้น หน่วยสตางค์ */
            price: number;
            /** @description ติดลบได้เฉพาะสินค้าพรีออเดอร์ (= ยอดที่ต้องสั่งผลิตเพิ่ม) */
            stockQuantity: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreateVariantDto: {
            /**
             * Format: uuid
             * @description id ของสินค้า (UUID)
             */
            productId: string;
            /** @description ชื่อตัวเลือก เช่น "M" */
            variantName: string;
            /** @description ราคาต่อชิ้น หน่วยสตางค์ */
            price: number;
            /** @description จำนวนคงเหลือเริ่มต้น */
            stockQuantity?: number;
        };
        UpdateVariantDto: {
            /** @description ชื่อตัวเลือก เช่น "M" */
            variantName?: string;
            /** @description ราคาต่อชิ้น หน่วยสตางค์ */
            price?: number;
            /** @description จำนวนคงเหลือเริ่มต้น */
            stockQuantity?: number;
        };
        UpdateStockDto: {
            /** @description จำนวนที่เพิ่ม (บวก) หรือลด (ลบ) */
            adjust?: number;
            /** @description กำหนดจำนวนคงเหลือใหม่ */
            set?: number;
        };
        /** @enum {string} */
        DeliveryMethod: "PICKUP" | "DELIVERY";
        /** @enum {string} */
        PaymentStatus: "PENDING" | "WAITING_VERIFY" | "PAID" | "REJECTED" | "REFUNDED";
        /** @enum {string} */
        OrderStatus: "PENDING" | "CONFIRMED" | "PREPARING" | "READY_FOR_PICKUP" | "SHIPPED" | "COMPLETED" | "CANCELLED";
        OrderItemProductModel: {
            imageUrl: string | null;
            id: string;
            name: string;
            category: string;
            isPreorder: boolean;
        };
        OrderItemVariantModel: {
            product: components["schemas"]["OrderItemProductModel"];
            id: string;
            variantName: string;
        };
        OrderItemModel: {
            variant: components["schemas"]["OrderItemVariantModel"];
            id: string;
            orderId: string;
            variantId: string;
            quantity: number;
            /** @description ราคาต่อชิ้น ณ ตอนสั่ง หน่วยสตางค์ */
            unitPrice: number;
            isPreorderItem: boolean;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        PickupLogEntryModel: {
            notes: string | null;
            id: string;
            orderId: string;
            staffCoreUserId: string;
            staffEmail: string;
            /** Format: date-time */
            pickupTime: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderModel: {
            deliveryMethod: components["schemas"]["DeliveryMethod"];
            shippingAddress: string | null;
            paymentSlip: string | null;
            paymentStatus: components["schemas"]["PaymentStatus"];
            orderStatus: components["schemas"]["OrderStatus"];
            /** @description รหัสรับสินค้า (เฉพาะ PICKUP) */
            pickupCode: string | null;
            shippingCarrier: string | null;
            trackingNumber: string | null;
            /** Format: date-time */
            shippedAt: string | null;
            orderItems: components["schemas"]["OrderItemModel"][];
            pickupLogs: components["schemas"]["PickupLogEntryModel"][];
            id: string;
            /** @description เช่น ORD-202609-0001 */
            orderNumber: string;
            /** @description เจ้าของคำสั่งซื้อ (claim `sub` ของ Core Hub) */
            coreUserId: string;
            customerEmail: string;
            recipientName: string;
            recipientPhone: string;
            /** @description ยอดรวม หน่วยสตางค์ */
            totalAmount: number;
            /** @description ค่าจัดส่ง หน่วยสตางค์ */
            shippingFee: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        OrderItemInputDto: {
            /**
             * Format: uuid
             * @description id ของตัวเลือกสินค้า
             */
            variantId: string;
            /** @description จำนวน */
            quantity: number;
        };
        CreateOrderDto: {
            /**
             * @description PICKUP = รับที่สาขา · DELIVERY = จัดส่ง
             * @enum {string}
             */
            deliveryMethod: "PICKUP" | "DELIVERY";
            /** @description ชื่อผู้รับ */
            recipientName: string;
            /** @description เบอร์โทร ตัวเลขล้วน 9–10 หลัก ไม่มีขีด */
            recipientPhone: string;
            /** @description ที่อยู่จัดส่ง — บังคับเมื่อ deliveryMethod = DELIVERY */
            shippingAddress?: string;
            /** @description URL หรือชื่อไฟล์สลิปโอนเงิน (แนบภายหลังได้) */
            paymentSlip?: string;
            /** @description รายการสินค้า */
            items: components["schemas"]["OrderItemInputDto"][];
        };
        UpdatePaymentStatusDto: {
            /**
             * @description สถานะการชำระเงินใหม่
             * @enum {string}
             */
            paymentStatus: "PENDING" | "WAITING_VERIFY" | "PAID" | "REJECTED" | "REFUNDED";
        };
        UpdateOrderStatusDto: {
            /**
             * @description สถานะคำสั่งซื้อใหม่
             * @enum {string}
             */
            orderStatus: "PENDING" | "CONFIRMED" | "PREPARING" | "READY_FOR_PICKUP" | "SHIPPED" | "COMPLETED" | "CANCELLED";
        };
        UpdateShippingDto: {
            /** @description รหัสบริษัทขนส่ง เช่น thailand_post / flash / kerry หรือชื่อขนส่งอื่น */
            shippingCarrier?: string;
            /** @description เลขพัสดุ */
            trackingNumber?: string;
            /** @description true (ค่าเริ่มต้น) = ใส่เลขพัสดุครั้งแรกแล้วเปลี่ยนสถานะเป็น SHIPPED ให้เลย */
            markShipped?: boolean;
        };
        UpdatePaymentSlipDto: {
            /** @description URL หรือชื่อไฟล์สลิปโอนเงิน */
            paymentSlip: string;
        };
        CreateOrderItemDto: {
            /**
             * Format: uuid
             * @description id ของตัวเลือกสินค้า
             */
            variantId: string;
            /** @description จำนวน */
            quantity: number;
        };
        UpdateOrderItemDto: {
            /** @description จำนวนใหม่ */
            quantity: number;
        };
        PickupLogOrderModel: {
            pickupCode: string | null;
            orderStatus: components["schemas"]["OrderStatus"];
            paymentStatus: components["schemas"]["PaymentStatus"];
            id: string;
            orderNumber: string;
            recipientName: string;
            customerEmail: string;
        };
        PickupLogModel: {
            notes: string | null;
            order: components["schemas"]["PickupLogOrderModel"];
            id: string;
            orderId: string;
            staffCoreUserId: string;
            staffEmail: string;
            /** Format: date-time */
            pickupTime: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
        };
        CreatePickupLogDto: {
            /**
             * Format: uuid
             * @description id ของคำสั่งซื้อ (ส่งอย่างใดอย่างหนึ่งกับ pickupCode)
             */
            orderId?: string;
            /** @description รหัสรับสินค้า เช่น PICKUP-123456 */
            pickupCode?: string;
            /** @description หมายเหตุ */
            notes?: string;
        };
        PickupVerificationModel: {
            order: components["schemas"]["OrderModel"];
            /** @description true = ส่งมอบได้ (ชำระแล้ว · ไม่ถูกยกเลิก · ยังไม่เคยรับ) */
            valid: boolean;
            alreadyPickedUp: boolean;
        };
        CreatePickupVerificationDto: {
            /** @description รหัสรับสินค้าที่ลูกค้าแสดง (สแกนจาก QR ได้) */
            pickupCode: string;
        };
        StatusCountModel: {
            status: string;
            count: number;
        };
        OrderStatsModel: {
            byOrderStatus: components["schemas"]["StatusCountModel"][];
            byPaymentStatus: components["schemas"]["StatusCountModel"][];
            totalOrders: number;
            /** @description ยอดขายที่ชำระแล้ว หน่วยสตางค์ */
            paidRevenue: number;
        };
        ProductImageModel: {
            id: string;
            /** @description ใส่ค่านี้ใน imageUrl ของสินค้า */
            url: string;
            contentType: string;
            size: number;
        };
        PaymentSlipModel: {
            id: string;
            /** @description ใส่ค่านี้ใน paymentSlip ของคำสั่งซื้อ (เปิดดูได้เมื่อเข้าสู่ระบบ) */
            url: string;
            contentType: string;
            size: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    HealthController_health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["HealthModel"];
                    };
                };
            };
        };
    };
    MeController_me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["MeModel"];
                    };
                };
            };
        };
    };
    ProductsController_findAll: {
        parameters: {
            query: {
                /** @description กรองตามหมวดหมู่ */
                category?: string;
                /** @description กรองเฉพาะพรีออเดอร์ (true) หรือพร้อมส่ง (false) */
                isPreorder?: boolean;
                /** @description ค้นจากชื่อหรือรายละเอียด */
                search?: string;
                /** @description หน้าที่ต้องการ เริ่มที่ 1 */
                page: number;
                /** @description จำนวนต่อหน้า 1–100 */
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProductModel"][];
                        meta: components["schemas"]["PageMetaModel"];
                    };
                };
            };
        };
    };
    ProductsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateProductDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProductModel"];
                    };
                };
            };
        };
    };
    ProductsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProductModel"];
                    };
                };
            };
        };
    };
    ProductsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedModel"];
                    };
                };
            };
        };
    };
    ProductsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateProductDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProductModel"];
                    };
                };
            };
        };
    };
    ProductCategoriesController_findAll: {
        parameters: {
            query: {
                /** @description หน้าที่ต้องการ เริ่มที่ 1 */
                page: number;
                /** @description จำนวนต่อหน้า 1–100 */
                limit: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProductCategoryModel"][];
                        meta: components["schemas"]["PageMetaModel"];
                    };
                };
            };
        };
    };
    ProductVariantsController_findAll: {
        parameters: {
            query: {
                /** @description หน้าที่ต้องการ เริ่มที่ 1 */
                page: number;
                /** @description จำนวนต่อหน้า 1–100 */
                limit: number;
                /** @description กรองตามสินค้า */
                productId?: string;
                /** @description เฉพาะตัวเลือกที่ยังมีของ */
                inStock?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["VariantWithProductModel"][];
                        meta: components["schemas"]["PageMetaModel"];
                    };
                };
            };
        };
    };
    ProductVariantsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateVariantDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["VariantWithProductModel"];
                    };
                };
            };
        };
    };
    ProductVariantsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["VariantWithProductModel"];
                    };
                };
            };
        };
    };
    ProductVariantsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedModel"];
                    };
                };
            };
        };
    };
    ProductVariantsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateVariantDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["VariantWithProductModel"];
                    };
                };
            };
        };
    };
    ProductVariantsController_updateStock: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateStockDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["VariantWithProductModel"];
                    };
                };
            };
        };
    };
    OrdersController_findAll: {
        parameters: {
            query: {
                /** @description หน้าที่ต้องการ เริ่มที่ 1 */
                page: number;
                /** @description จำนวนต่อหน้า 1–100 */
                limit: number;
                orderStatus?: "PENDING" | "CONFIRMED" | "PREPARING" | "READY_FOR_PICKUP" | "SHIPPED" | "COMPLETED" | "CANCELLED";
                paymentStatus?: "PENDING" | "WAITING_VERIFY" | "PAID" | "REJECTED" | "REFUNDED";
                deliveryMethod?: "PICKUP" | "DELIVERY";
                /** @description ค้นจากเลขที่คำสั่งซื้อ รหัสรับสินค้า เลขพัสดุ ชื่อหรืออีเมลผู้สั่ง */
                search?: string;
                /** @description เลขที่คำสั่งซื้อแบบตรงตัว เช่น ORD-202609-0001 */
                orderNumber?: string;
                /** @description true = เฉพาะคำสั่งซื้อของฉัน (เจ้าหน้าที่ใช้ดูของตัวเอง) */
                mine?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderModel"][];
                        meta: components["schemas"]["PageMetaModel"];
                    };
                };
            };
        };
    };
    OrdersController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderModel"];
                    };
                };
            };
        };
    };
    OrdersController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderModel"];
                    };
                };
            };
        };
    };
    OrdersController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedModel"];
                    };
                };
            };
        };
    };
    OrdersController_updatePaymentStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePaymentStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderModel"];
                    };
                };
            };
        };
    };
    OrdersController_updateOrderStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderStatusDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderModel"];
                    };
                };
            };
        };
    };
    OrdersController_updateShipping: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateShippingDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderModel"];
                    };
                };
            };
        };
    };
    OrdersController_updatePaymentSlip: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePaymentSlipDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderModel"];
                    };
                };
            };
        };
    };
    OrdersController_findItems: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderItemModel"][];
                        meta: components["schemas"]["PageMetaModel"];
                    };
                };
            };
        };
    };
    OrdersController_addItem: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateOrderItemDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderItemModel"];
                    };
                };
            };
        };
    };
    OrderItemsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderItemModel"];
                    };
                };
            };
        };
    };
    OrderItemsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedModel"];
                    };
                };
            };
        };
    };
    OrderItemsController_update: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateOrderItemDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderItemModel"];
                    };
                };
            };
        };
    };
    PickupLogsController_findAll: {
        parameters: {
            query: {
                /** @description หน้าที่ต้องการ เริ่มที่ 1 */
                page: number;
                /** @description จำนวนต่อหน้า 1–100 */
                limit: number;
                orderId?: string;
                /** @description กรองตามเจ้าหน้าที่ผู้บันทึก (core_user_id) */
                staffCoreUserId?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PickupLogModel"][];
                        meta: components["schemas"]["PageMetaModel"];
                    };
                };
            };
        };
    };
    PickupLogsController_create: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePickupLogDto"];
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PickupLogModel"];
                    };
                };
            };
        };
    };
    PickupLogsController_findOne: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PickupLogModel"];
                    };
                };
            };
        };
    };
    PickupLogsController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedModel"];
                    };
                };
            };
        };
    };
    PickupVerificationsController_verify: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePickupVerificationDto"];
            };
        };
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PickupVerificationModel"];
                    };
                };
            };
        };
    };
    OrderStatsController_summary: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["OrderStatsModel"];
                    };
                };
            };
        };
    };
    ProductImagesController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["ProductImageModel"];
                    };
                };
            };
        };
    };
    ProductImagesController_remove: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["DeletedModel"];
                    };
                };
            };
        };
    };
    PaymentSlipsController_upload: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
            };
        };
        responses: {
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @enum {boolean} */
                        success: true;
                        data: components["schemas"]["PaymentSlipModel"];
                    };
                };
            };
        };
    };
}
